---
- hosts: ansible_machine
  become: false
  vars:
    - ansible_python_interpreter: /home/arlaporte/virtual_environments/ansible_osp_ws/bin/python3
    - osp_cloud: overcloud
    - create_project_security_groups: true
    - osp_sec_groups:
      - secgroup_name: allow_ssh_web_test
        secgroup_owner_project: smurf_labs
        sec_group_rules:
          - direction: ingress
            source_network: 0.0.0.0/0
            port_range_min: 22
            port_range_max: 22
            protocol: tcp
          - direction: ingress 
            source_network: 0.0.0.0/0
            port_range_min: 80
            port_range_max: 80
            protocol: tcp
          - direction: ingress 
            source_network: 0.0.0.0/0
            port_range_min: 443
            port_range_max: 443
            protocol: tcp
          - direction: ingress 
            source_network: 0.0.0.0/0
            port_range_min: -1
            port_range_max: -1
            protocol: tcp

  tasks:
    - name: "Creating project security groups."
      os_security_group:
        cloud: "{{ osp_cloud }}"
        name: "{{ item.secgroup_name }}" 
        project: "{{ item.secgroup_owner_project }}"
        state: present
      loop: "{{ osp_sec_groups }}"
      when: create_project_security_groups == True 
      tags:
        - create_security_group

    - name: "Creating project security group rules."
      os_security_group_rule:
        cloud: "{{ osp_cloud }}"
        security_group: "{{ item.0.secgroup_name }}"
        project: "{{ item.0.secgroup_owner_project }}"
        protocol: "{{ item.1.protocol }}"
        remote_ip_prefix: "{{ item.1.source_network }}"
        port_range_min: "{{ item.1.port_range_min }}"
        port_range_max: "{{ item.1.port_range_max }}"
        state: present
      with_subelements: 
        - "{{ osp_sec_groups }}"
        - sec_group_rules
      when: create_project_security_groups == True 
      tags:
        - create_security_group
